### ISSUE TITLE
core/error: core.frag: Shader compile error.

### ISSUE THREAD

**Issue by Git-Forked** [performous/performous#697] opened 2022-02-19 11:12 UTC
core/notice: Performous 1.1+ starting...
  Internationalization: Enabled
  MIDI Hardware I/O:    Enabled
  Webcam support:       Enabled
core/notice: Starting the audio subsystem (errors printed on console may be ignored).
audio/error: Audio device 'dev="USBMIC" mics="blue,red"': No such device.
audio/error: Audio device 'dev="Microphone" mics="*"': No such device.
audio/error: Audio device 'out=2': Device doesn't have enough output channels
opengl/error: Shader color: 0:24(22): warning: `i' used uninitialized
0:25(23): warning: `i' used uninitialized
0:26(23): warning: `i' used uninitialized
0:27(19): warning: `i' used uninitialized
0:28(17): warning: `i' used uninitialized

opengl/error: Shader color: 0:11(1): error: `in' qualifier in declaration of `bogus' only valid for function parameters in GLSL 1.20

core/error: core.frag: Shader compile error.

**Comment by Baklap4** [comment] 2022-02-21 08:52
Closing this since it's a duplicate of #566  Continue the discussion there please

**Closed by Baklap4** 2022-02-21 08:52 UTC
