### ISSUE TITLE
Missing characters from the font?

### ISSUE THREAD

**Issue by skyli91** [performous/performous#200] opened 2016-07-03 17:30 UTC
![image](https://cloud.githubusercontent.com/assets/7442913/16546746/96337796-4154-11e6-8588-e25d123a7df6.png)

**Comment by nieknooijens** [comment] 2016-07-05 07:15
those are special UTF-8 chars and it really comes down to the font, on linux/mac they're automatically available, but on windows we don't know which fonts are installed and which aren't.
this is how it is supposed to look and how it looks on my linux machine:
![schermafdruk van 2016-07-05 09-14-26](https://cloud.githubusercontent.com/assets/2794331/16576682/0bdc0840-4291-11e6-8b1e-8e9fe37fdacf.png)

**Comment by skyli91** [comment] 2016-07-05 07:53
is it possible to include that font too and not use a system font which is not present in windows?

**Comment by nieknooijens** [comment] 2016-07-05 08:30
well... the funny part is that it isn't a system font, linux just checks whether a font supports these symbols and if it doesn't it just loads those symbols from a different font.
for example, if I install "unifont" which has the thai alphabet, it will only use that font when the thai alphabet is actually used.

**Comment by skyli91** [comment] 2016-07-05 10:43
Aha, then i think i can fix it using font creator and put these in the font :)

**Comment by skyli91** [comment] 2016-07-05 10:44
btw i don't really like these fonts >< not too readable if you have bad eyes.

**Comment by nieknooijens** [comment] 2016-07-05 10:56
ok, just send a pull request and we'll take a look at it. I think they're fine, much better than the average youtube karaoke vid :stuck_out_tongue_closed_eyes:

**Comment by sophof** [comment] 2016-09-20 13:40
It's not really clear to me how to fix this issue, can you elaborate skyli91?

According to the 1.1 release notes: •Fixed font loading: Pango is now used on all platforms, so Performous should look the same everywhere

So I'd assume this should be fixed?

**Comment by nieknooijens** [comment] 2017-01-22 14:49
I guess so

**Comment by Stefan1200-de** [comment] 2017-06-27 11:34
I still have this issue with Performous 1.1 on Windows 10 x64, using German game language.

If I can help somehow, feel free to ask me.

**Comment by basisbit** [comment] 2017-06-27 15:35
please upload an example txt file, so we can reproduce this issue

**Comment by Stefan1200-de** [comment] 2017-06-27 15:44
Oh, nothing from a song txt file. I have the same issue as @skyli91 from his screenshot at the starting post.

**Comment by Baklap4** [comment] 2017-06-27 16:20
quoted from @nieknooijens 

> well... the funny part is that it isn't a system font, linux just checks whether a font supports these symbols and if it doesn't it just loads those symbols from a different font.
for example, if I install "unifont" which has the thai alphabet, it will only use that font when the thai alphabet is actually used.

**Comment by Stefan1200-de** [comment] 2017-06-27 16:31
@Baklap4 well, that still does not fix the issue. @sophof mentioned from the 1.1 changelog, that Performous use an own font, I guess this font have this symbols. Why they are not displayed on Windows? And if this can't be fixed with the current method, the Windows version needs another solution.

**Comment by basisbit** [comment] 2017-06-27 18:31
indeed, can confirm this issue with latest master

**Comment by basisbit** [comment] 2017-06-27 18:47
Could this be caused by a text file reading encoding problem?
![image](https://user-images.githubusercontent.com/10870269/27604443-93ead228-5b79-11e7-9a7e-fb31e8d4e59b.png)
this happens for a UTF8 encoded file with BOM and these tags:
#ENCODING:UTF8
#TITLE:Mirai Start
#ARTIST:マイリトルポニー

**Comment by nieknooijens** [comment] 2017-06-28 06:42
that ENCODING tag gets ignored :rofl: 
best on windows is to use notepad++ and save it under a different name as UTF8 with LF line endings.
or use the "fix-songfiles.sh" in the scripts folder, but be awared that this might screw up some characters!

**Comment by nieknooijens** [comment] 2017-06-28 06:50
@basisbit I'm not really suggesting to fix encodings, I want to rule out some stuff. I want to be 100% certain that it's not a textfile mis-interpretation.

**Comment by basisbit** [comment] 2017-06-28 06:57
converted the file to UTF8 without BOM using notepad++ and the issue was still happening

**Comment by Lord-Kamina** [comment] 2017-07-29 17:12
So... I was looking for this issue the other day in other to post an update and just couldn't find it.
I've traced the cause of this issue to us shipping an incomplete (or rather non-existant) Fontconfig configuration. It should be more-or-less trivial to fix.

**Comment by TobiX** [comment] 2017-07-29 17:39
Ah right, I also took a look at the problem: When not shipping a config files on systems that don't use fontconfig natively (Windows, OS X), fontconfig can't fall back to system fonts (since it doesn't know where they are). There are different fixes for this:

1. Shipping enough fonts so that all glyphs are covered (can become quite large if we want to cover CJK glyphs) - but we should at least cover our UI element ;)
2. Ship a fontconfig file to allow it to fall back to system fonts
3. Supply the one or two settings needed on those platforms in code

The second option probably being the simplest.

**Closed** 2017-10-02 13:43 UTC
Labels: bug, can't reproduce, platform specific bug

**Comment by Baklap4** [comment] 2021-08-13 16:08
It seems this issue is caused by crosscompiling from linux to windows without properly configuring fontconfig.
Currently we have a open pr for a native windows build which fixes this problem when built natively.

I tried out the `FileWithEncodingProblem` from @basisbit and didn't see any issues. Also i've checked the songbrowser itself and i did see the arrow characters.

![image](https://user-images.githubusercontent.com/3918517/129387686-d7fba2e6-fe65-4775-ad83-cc3aaab78c17.png)

So please checkout #650 and build + try for yourselves.
