### ISSUE TITLE
One last crash; possibly caused by a zombie reference?

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#300] opened 2017-11-12 16:26 UTC
Ok, am done with this one...

[performous_2017-11-12-034917_Anasas.crash.log](https://github.com/performous/performous/files/1464874/performous_2017-11-12-034917_Anasas.crash.log)

**Comment by Baklap4** [comment] 2018-02-01 16:44
@Lord-Kamina As per your log i think it happened during deletion of a song from the current playlist.

```
Thread 7:
0   performous                    	0x0000000107aaf113 PlayList::removeSong(int) + 51
1   performous                    	0x0000000107b2063f WebServer::POSTresponse(boost::network::http::basic_request<boost::network::http::tags::http_server> const&) + 2127
```
Can you confirm if this is still present in the current UI?

Also if it still exists, can you confirm what has been send as request body?

**Comment by Lord-Kamina** [comment] 2018-02-01 16:48
I haven't been able to reproduce it but this doesn't mean it's not really there... honestly, don't know.

**Comment by Baklap4** [comment] 2018-03-16 08:25
Closing this due to not be able to reproduce this.

If you happen to face this again, please check the request send to the server and post the body over here.

**Closed by Baklap4** 2018-03-16 08:25 UTC
Labels: Bug
