### ISSUE TITLE
Build on macOS Sierra fails

### ISSUE THREAD

**Issue by MagicChocoRolls** [performous/performous#207] opened 2016-11-14 12:45 UTC
Hi there,

I get an error when trying to build performous on macOS Sierra. I use the newest macOS Patches and XCode. I ran the build code from the wiki and it fails when executing the following line:
`sudo port install -sR libsigcxx2 configure.compiler=macports-gcc-4.8`

It says `Error: org.macports.build for port m4 returned: command execution failed
Error: Failed to install m4`

What I wanted to do is use the internal webserver with macOS :) Is there a working build or can someone help me fix that?

Regards

**Comment by nieknooijens** [comment] 2016-11-14 12:54
@Lord-Kamina should know about this.

**Comment by Lord-Kamina** [comment] 2016-12-02 01:34
Honestly I haven't tried to install on Sierra but shouldn't be using gcc. Try building on Clang.

**Comment by MagicChocoRolls** [comment] 2016-12-20 09:36
Clang seems to work. Now I am working on getting cpp-netlib included. I want the webserver to work :)

**Comment by MagicChocoRolls** [comment] 2016-12-20 10:31
I copied the asio files to /opt/local/include and /opt/local/include/boost. It runs further now, but doesn't complete.

`2 errors generated.
make[2]: *** [game/CMakeFiles/performous.dir/main.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
9 errors generated.
make[2]: *** [game/CMakeFiles/performous.dir/screen_intro.cc.o] Error 1`


Anyone here to help me? Any suggestions?

**Comment by Lord-Kamina** [comment] 2016-12-20 14:28
Are you using the premade command-file in `osx-utils`? You should first and
foremost try that, and then attempt to modify it to suit your needs.

**Comment by MagicChocoRolls** [comment] 2016-12-20 14:30
oh yes, I do. I followed the wiki instructions for the dependencies and installed some more that were not mentioned (e.g. npm and the dmg creator).
basically, I installed all dependencies from the wiki and ran the script in osx-utils.

**Comment by Lord-Kamina** [comment] 2016-12-20 14:30
Also, you should post the entire log because what you posted is not the
actual error, but rather a "there was an error upstream, stopping" message.

**Comment by Lord-Kamina** [comment] 2016-12-20 14:33
The most common cause of failure is due to some macports dependencies being
compiled against libstdc++ instead of libc++. Generally what I do is
manually specify overrides for libc++ when building dependencies.

Nonetheless, I haven't actually tried compiling under Sierra so it IS
possible that there could be a new error.

**Comment by MagicChocoRolls** [comment] 2016-12-20 14:42
Here is my compile log. 
[log.txt](https://github.com/performous/performous/files/663937/log.txt)

In my humble opinion, they do not seem that critical, but I am not really doing that on a daily basis :D

PS: When you try compiling again for a new version, I would love to see the webserver integrated, even if it will be disabled by default or something :)

**Comment by Lord-Kamina** [comment] 2017-02-12 03:53
I've been reproducing this bug today. The asio part is because of a (I think, at least, technically) incorrect include path in some cpp-netlib headers. They include <asio/whatever> instead of <boost/asio/whatever>, running a search/replace on all the cpp-netlib fixes that, but it still won't compile.

Here's the actual error; although I don't think it's a problem with performous, rather it seems to be an issue of cpp-netlib.

```bash
In file included from /Users/Koji/performous/game/webserver.hh:4:
In file included from /opt/local/include/boost/network/protocol/http/server.hpp:15:
In file included from /opt/local/include/boost/network/protocol/http/server/async_server.hpp:15:
/opt/local/include/boost/network/protocol/http/server/socket_options_base.hpp:46:12: error: no matching member function for call to 'set_option'
    socket.set_option(linger, ignored);
```

```bash
In file included from /Users/Koji/performous/game/webserver.hh:4:
In file included from /opt/local/include/boost/network/protocol/http/server.hpp:15:
/opt/local/include/boost/network/protocol/http/server/async_server.hpp:169:58: error: no matching member function for call to 'resolve'
    tcp::resolver::iterator endpoint_iterator = resolver.resolve(query, error);
```

and

```bash
In file included from /Users/Koji/performous/game/main.cc:16:
/Users/Koji/performous/game/webserver.hh:45:15: error: no type named 'response' in 'boost::network::http::server<WebServer::handler>'
        http_server::response GETresponse(http_server::request const &request);
```

**Comment by Lord-Kamina** [comment] 2017-02-12 16:30
I'm making some progress here. I downloaded the standalone ASIO library and compiled it, then built cpp-netlib against that and there was definitely some improvement, as now all the cpp-netlib tests passed (before, 3 tests regarding the http client were failing) but performous still won't build.

These are the relevant errors:

```bash
/Users/Koji/performous/game/webserver.hh:45:15: error: no type named 'response' in 'boost::network::http::server<WebServer::handler>'
        http_server::response GETresponse(http_server::request const &request);
        ~~~~~~~~~~~~~^
/Users/Koji/performous/game/webserver.hh:46:15: error: no type named 'response' in 'boost::network::http::server<WebServer::handler>'
        http_server::response POSTresponse(http_server::request const &request);
```

**Comment by nieknooijens** [comment] 2017-02-12 18:40
isn't this related to #201 ?

**Comment by Lord-Kamina** [comment] 2017-02-12 18:42
@nieknooijens Yes, it's basically the same issue. It is related to some structs and types changing names between cpp-netlib 0.11.2 and 0.12.0.

**Comment by MagicChocoRolls** [comment] 2017-02-12 19:52
Thank you for the update :) So it looks like I could be successful building against 0.11.2 instead of 0.12.0, that'll ne worth a try.

**Comment by Baklap4** [comment] 2017-06-26 19:51
@Lord-Kamina Please a status update, since you are currently using sierra?

**Comment by Lord-Kamina** [comment] 2017-06-26 22:19
Build is ok on Sierra. Had to move to boost 1.60 (now using 1.62 but it's the same, really)... otherwise, everything's ok.

**Comment by Baklap4** [comment] 2017-06-26 22:22
Alright then i'm closing this :+1:

**Closed by Baklap4** 2017-06-26 22:22 UTC
Labels: bug

**Comment by MagicChocoRolls** [comment] 2017-06-28 15:45
Update from me as I am the requester:

Build on Sierra works like a charm, but the Wiki is completely outdated :(
I have some notes on how to build performous on macOS Sierra, which might help others to do so.

**Comment by Baklap4** [comment] 2017-06-28 16:02
@MagicChocoRolls would be lovely to share it on the wiki :+1:

**Comment by MagicChocoRolls** [comment] 2017-06-28 16:24
@Baklap4 Done :)
I think someone should cross-check the instructions and maybe delete the old OS X instructions. I left them there and created "new ones" for macOS.

**Comment by Baklap4** [comment] 2017-06-28 16:37
@Lord-Kamina can you try these new OSX build steps out?

**Comment by Lord-Kamina** [comment] 2017-06-28 17:08
Will do.

**Comment by Lord-Kamina** [comment] 2017-07-01 01:21
@MagicChocoRolls I have expanded and updated your build instructions as per my own procedure; I corrected some important things re:cpp-netlib, you should try following my instructions (at least regarding asioc++ and cpp-netlib) as an incorrect build might be the actual cause for your trouble with the webserver.
