### ISSUE TITLE
What is performous doing after loading songs?

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#224] opened 2017-02-15 00:53 UTC
I was building yesterday to test the webserver on OSX and, after songs are loaded, performous would be seemingly stuck on a black screen and a spinning beachball; I thought there was something wrong with the build but after a few minutes it worked and subsequent runs didn't have that delay.

I don't know if it's building the font caché or what, but it might be a good idea to add some output to the log as it would otherwise appear to be frozen for a couple minutes on first run.

**Comment by nieknooijens** [comment] 2017-02-15 07:38
The loading of songs is done on a seperate thread, after that it does nothing. When I boot performous and open the song browser I see covers just pop in at random because they are loaded async.
Font-cache and banner cache are a completely different thing though.. they run on the GUI thread because the GUI needs them. It would probably be appropriate to dump a popup on screen telling the user that it's "loading resources" before actually start loading it.

**Comment by Lord-Kamina** [comment] 2017-02-15 12:36
So it was probably those caches, considering they occurred before the gui
actually showed. It would probably be a good idea to add a pop-up and/or
notification so it doesn't appear to be dead

**Comment by Baklap4** [comment] 2020-04-09 18:57
@Lord-Kamina still a problem? If not let's close this
I don't see this with current master..

**Comment by Baklap4** [comment] 2021-08-06 13:53
Auto closing this stale issue. If the issue is still a thing please reopen this @Lord-Kamina

**Closed by Baklap4** 2021-08-06 13:53 UTC
Labels: Enhancement
