### ISSUE TITLE
failure to compile on linux

### ISSUE THREAD

**Issue by jose1711** [performous/performous#288] opened 2017-09-09 14:11 UTC
i am unable to build performous (current git) on arch linux:

```
[ 14%] Building CXX object game/CMakeFiles/performous.dir/webserver.cc.o
/home/jose/tarballs/aur4/performous-git/src/performous-git/game/webserver.cc:351:1: error: redefinition of ‘WebServer::WebServer(Songs&)’
 WebServer::WebServer(Songs& songs)
 ^~~~~~~~~
In file included from /home/jose/tarballs/aur4/performous-git/src/performous-git/game/webserver.cc:1:0:
/home/jose/tarballs/aur4/performous-git/src/performous-git/game/webserver.hh:63:2: note: ‘WebServer::WebServer(Songs&)’ previously defined here
  WebServer(Songs&) {}
  ^~~~~~~~~
/home/jose/tarballs/aur4/performous-git/src/performous-git/game/webserver.cc:353:23: error: definition of implicitly-declared ‘WebServer::~WebServer()’
 WebServer::~WebServer(){}
                       ^
make[2]: *** [game/CMakeFiles/performous.dir/build.make:1575: game/CMakeFiles/performous.dir/webserver.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: game/CMakeFiles/performous.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

any idea?

**Comment by Lord-Kamina** [comment] 2017-09-09 19:56
What compiler are you using? It seems to be an issue with the preprocessor macros. i.e. it appears it's ignoring them.

**Comment by jose1711** [comment] 2017-09-09 21:02
gcc 7.1.1, cmake 3.8.2, make 4.2.1

**Comment by Lord-Kamina** [comment] 2017-09-09 21:28
I have no idea why would it fail... try some version of gcc6 perhaps, or maybe clang?

I'm pretty sure it's a compiler issue. The problem is it seems to be ignoring the preprocessor directives and thus it thinks something is defined twice because it's trying to compile both cases at the same time.

**Comment by Lord-Kamina** [comment] 2017-09-12 14:26
@jose1711  Did you manage to fix this?

**Comment by jose1711** [comment] 2017-09-12 14:51
i am failing to build older versions of gcc so the answer is no

**Comment by Baklap4** [comment] 2017-09-12 15:49
I'm using the following setup and it works correctly:
Gcc 6.3.0 20170406
cmake 3.7.2
make 4.1
Ubuntu 17.04

Our ci which uses Ubuntu 14.04.5 builds it flawlessly aswell with either gcc or clang: https://semaphoreci.com/performous/performous/branches/master/builds/81

**Comment by Baklap4** [comment] 2017-10-03 15:58
@performous/contributors can someone try to build with the setup @jose1711 mentioned (on linux)? I'm currently not availble for trying this since i'm facing connectivity issues and hdd space issues

**Comment by ShalokShalom** [comment] 2017-10-05 09:53
I use the gcc 6.4.0 here, with cmake 3.9.3 and make 4.2.1 on KaOS

See also: https://github.com/performous/performous/issues/291#issuecomment-334284499

**Comment by Baklap4** [comment] 2017-11-03 21:03
Guys i think i've found the problem. Since the webserver is included within master one has to have cppnetlib available. From our docs i've read the following:
> Note: when building the webserver-branch you need CPP-netlib get the latest version from:http://cpp-netlib.org/ and unpack the folder named "boost" into /usr/include. if done correctly you should have the file: /usr/include/boost/network/protocol/http/server.hpp among some others.

This is correct version of cpp-netlib which it works for me with: https://github.com/cpp-netlib/cpp-netlib/archive/cpp-netlib-0.11.2-final.tar.gz

As our docs state copy the contents of the boost folder to `/usr/include/boost` and you're good to go while building with gcc 7.2.0 (at least i was)

**Comment by jose1711** [comment] 2017-11-04 16:05
installed cpp-netlib 0.11.2 and compilation is now failing at 34 %.
```
[ 34%] Building CXX object game/CMakeFiles/performous.dir/log.cc.o
[ 34%] Building CXX object game/CMakeFiles/performous.dir/main.cc.o
In file included from /tmp/performous-git/src/performous-git/game/main.cc:17:0:
/tmp/performous-git/src/performous-git/game/webserver.hh:44:15: error: ‘response’ in ‘WebServer::http_server {aka struct boost::network::http::server<WebServer::handler>}’ does not name a type
  http_server::response GETresponse(http_server::request const &request, std::string& content_type);
               ^~~~~~~~
/tmp/performous-git/src/performous-git/game/webserver.hh:45:15: error: ‘response’ in ‘WebServer::http_server {aka struct boost::network::http::server<WebServer::handler>}’ does not name a type
  http_server::response POSTresponse(http_server::request const &request);
               ^~~~~~~~
make[2]: *** [game/CMakeFiles/performous.dir/build.make:663: game/CMakeFiles/performous.dir/main.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: game/CMakeFiles/performous.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by Lord-Kamina** [comment] 2017-11-05 22:19
@jose1711 that should be fixed eventually but is not a priority. The reason for that failure is the cpp-netlib API changed between 0.11.2 and 0.12 and that is what breaks the build.

**Comment by nieknooijens** [comment] 2017-11-06 08:58
ubuntu 17.10 doesn't even feature a cpp-netlib package anymore, I had to install the one from 17.04...

**Comment by Lord-Kamina** [comment] 2017-11-06 13:26
I think an acceptable middle ground for now is checking at build-time the
version of cpp-netlib in the environment and adjust accordingly? I don't
think the change is particularly large but as I recall it changed the
signature of one of the methods we're using.

**Comment by ShalokShalom** [comment] 2018-02-10 18:05
Does this checking at build time happen now?

**Comment by Lord-Kamina** [comment] 2018-02-12 15:33
No it doesn't because most of everybody's building environments include
cpp-netlib 0.11. The new versions of these have dropped cpp-netlib entirely
in fact. So, we will most likely scrap it altogether in favor of boost
networking, but AFAIK work has not yet begun on that.

--

**Comment by ShalokShalom** [comment] 2018-02-13 06:25
Ah I see

**Comment by Baklap4** [comment] 2018-03-19 22:31
Closing this since i just made a change on the wiki saying we depend on 0.11.2 for now: https://github.com/performous/performous/wiki/Building-and-installing-from-source/_compare/84a792316177e271a4e45675c13996d6a9f23d36...62dda5a5b19bb2e085ef286ccc7c191505943137

Discussion regarding cppnetlib or boost is held at #306 please continue there.

**Closed by Baklap4** 2018-03-19 22:31 UTC
Labels: Bug, Has Workaround
