### ISSUE TITLE
Compiling for Open GL ES (on an ARM platform)?

### ISSUE THREAD

**Issue by poVoq** [performous/performous#147] opened 2015-06-14 07:36 UTC
I have an ODROID-X2 (Quadcore 1.8ghz ARMv7, 2gb ram and a Mali400 GPU) running on Lubuntu 14.04 here, that I would like to use for Performous, but the Mali driver only supports OpenGL ES.

In the compiling instructions it says that regular OpenGL is required, but I read somewhere that recently some work was done to run it on an RasberryPI which also only supports OpenGL ES.

Any pointers how to compile it for such an ARM development board?

Otherwise, might it work with GLshim: https://github.com/lunixbochs/glshim ?

**Comment by nieknooijens** [comment] 2015-06-15 06:22
we recently ported performous to libepoxy which should be compatible with openGL ES if i'm correct.
SDL2 should also just support it, but other than that we haven't tested a setup like that before.
I would really like to help, but I don't have a suitable ARM platform to test this with. Guess I need to buy one of those raspberry-pi 2's since they are fast enough to run performous (I have 4 V1's and 2 V1 B+'s but they all have that slow 700MHz chip)

**Comment by poVoq** [comment] 2015-06-15 11:42
So if I have an SDL2 all configured for OGL ES it should just compile and run, or do I need to do any special configuration before compiling?

**Comment by nieknooijens** [comment] 2015-06-15 11:46
don't really know, I've never tried. we did carefully choose our libraries with the ARM/GLES goal in mind but we've never tried mostly because we don't have the hardware currently.
I think cmake should take care of the configuration stuff but i'm not entirely sure.

**Comment by TobiX** [comment] 2015-06-16 14:46
The Raspberry Pi 2 GL implementation is a real pain in the posterior. I tried to get it to compile on ArchLinuxArm, but gave up on it since I couldn't figure out how to get it to work. Maybe sometime in the future there will be a real MESA backend for the Raspberry Pi graphics chip, but until then I keep my sanity and away from this stuff...

**Comment by meden** [comment] 2015-11-14 13:51
Helo, I'm trying to get Performous running on Odroid-U3. I compiled and installed the Performous  `master` branch and I rebuilt libSDL2 Ubuntu packages with `--disable-video-opengl` to be sure the library is using OpenGL ES.

When I run Performous I get
> core/error: OpenGL 2.1 is required but not available

It seems that Performous has an hard requirement on OpenGL >= 2.1, despite using libSDL2 as abstraction layer.

**Comment by TobiX** [comment] 2015-11-14 17:36
Try disabling that check and see where it fails next. This is mostly a sanity check to fail as early as possible. I suspect you have to rewrite some of the shaders and convince libepoxy to not use desktop OpenGL if your system provides it...

**Comment by Baklap4** [comment] 2018-03-29 20:40
Closing this as a duplicate of #17 
If any objection feel free to reopen it or create a new issue.

**Closed by Baklap4** 2018-03-29 20:40 UTC
Labels: Duplicate, Enhancement, Platform Specific Bug, Question
