### ISSUE TITLE
Performous, avformat-59.dll crashes when loading songs from networked filesystem, Win 10 Pro 22H2

### ISSUE THREAD

**Issue by floridop** [performous/performous#919] opened 2023-09-30 10:14 UTC
### Performous & operating system versions

Performous: 1.3.0 and latest from one week before this submission
Operating system: Windows 10 Pro 22H2/2020 x64

### What is the problem?

Program starts with no problem without parameters  
It is installed in a USB external `E:\games\performous\`

I have all the songs on a samba networked filesystem on NAS on `Z:\UltrastarSongs`
The folder structure is as such

```
Z:\UltrastarSongs
  - > Ultrastar Base
  - > Rock songs
  - > Some random collection

Starting with:
```console
E:\games\Performous>Performous.exe Z:\UltrastarSongs
```
The program starts and crashed few seconds after while scanning the folder(s)

I tried passing individual folders but the problem is the same

Eventlog shows that the crash happens on this dll:

`avformat-59.dll`

### Steps to reproduce

1. Install performous on an external disk
2. Start performous once, check that it works
3. Start perfomous with a path to an external samba-mounted folder such as ```Performous.exe Z:\UltrastarSongs```
4. Program opens and crashes in around 2 seconds, I can see the scanning started by the blinking lights in the networked NAS
5. Check eventlog

### Additional context

It seems to me the problem us the A/V decoding, maybe the networked fs causes delays/slowdown that crash the lib.

I can provide more logs if needed.

Eventlog for 1.3.0:

```
Faulting application name: Performous.exe, version: 1.3.0.0, time stamp: 0x64f57d2b
Faulting module name: avformat-59.dll, version: 0.0.0.0, time stamp: 0x64f4e6d5
Exception code: 0xc0000005
Fault offset: 0x000000000002fbbe
Faulting process ID: 0x2860
Faulting application start time: 0x01d9f3819571d99e
Faulting application path: E:\games\Performous\Performous.exe
Faulting module path: E:\games\Performous\avformat-59.dll
Report ID: 19fb4fa2-641c-4dc8-90f9-c0bc29cb1219
Faulting package full name: 
Faulting package-relative application ID: 
```

Eventlog for 1.3.0.7:
```
Faulting application name: Performous.exe, version: 1.3.0.7, time stamp: 0x651085c6
Faulting module name: avformat-59.dll, version: 0.0.0.0, time stamp: 0x6510682e
Exception code: 0xc0000005
Fault offset: 0x000000000002fbbe
Faulting process ID: 0x25cc
Faulting application start time: 0x01d9f383ac640fc7
Faulting application path: E:\games\Performous\Performous.exe
Faulting module path: E:\games\Performous\avformat-59.dll
Report ID: 4a8236ba-1870-4b17-bee0-ffb2e06fd550
Faulting package full name: 
Faulting package-relative application ID: 
```

The same version works on Linux but the songs folder is mounted via nfs.

### Log(s) & preferences file(s)

[infolog.txt](https://github.com/performous/performous/files/12774408/infolog.txt)
[config.xml.txt](https://github.com/performous/performous/files/12774414/config.xml.txt)

**Comment by HetorusNL** [comment] 2023-10-01 15:40
This might be an instance of #893 .
Do you have the 'Beta: Use Unicode UTF-8 for worldwide language support' option enabled in windows, if you have non-ascii characters in song names or paths? (for information see the release notes of the 1.3.0 release).

**Comment by Baklap4** [comment] 2023-10-02 17:18
duplicate of #893 . Closing it since we already have a ticked for this. Had it this weekend when attempting to load songs from within a special character folder
For windows please enable the Beta Use Unicode UTF-8 Support -> 

1. Windows btn + R -> intl.cpl
2. Hit the 2nd tab called "administritive"
3. Hit the button "Change System Locale..."
4. Tick the checkbox "Beta: Use Unicode UTF-8 for worldwide language support"
5. Restart pc

**Closed by Baklap4** 2023-10-02 17:18 UTC
Labels: Bug
