### ISSUE TITLE
Segmentation fault: Not found: Steven Dunston - Northern Star.MPG

### ISSUE THREAD

**Issue by ShalokShalom** [performous/performous#291] opened 2017-09-18 18:39 UTC
```
(gdb) run
Starting program: /usr/bin/performous 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0x7fffd90d2700 (LWP 31324)]
logger/notice: Logging all notices, warnings and errors. Log file: /home/matthias/.cache/performous/infolog.txt
core/notice: Performous 1.1+ starting...
  Internationalization: Enabled
  MIDI Hardware I/O:    Enabled
  Webcam support:       Enabled
core/notice: Starting the audio subsystem (errors printed on console may be ignored).
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=0'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=0'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=0'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=0'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM phoneline
[New Thread 0x7fffd1c5a700 (LWP 31325)]
[Thread 0x7fffd1c5a700 (LWP 31325) exited]
[New Thread 0x7fffd1c5a700 (LWP 31326)]
[Thread 0x7fffd1c5a700 (LWP 31326) exited]
[New Thread 0x7fffd1c5a700 (LWP 31327)]
[Thread 0x7fffd1c5a700 (LWP 31327) exited]
[New Thread 0x7fffd1c5a700 (LWP 31328)]
[Thread 0x7fffd1c5a700 (LWP 31328) exited]
[New Thread 0x7fffd1c5a700 (LWP 31329)]
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
[Thread 0x7fffd1c5a700 (LWP 31329) exited]
audio/error: Audio device 'dev="USBMIC" mics="blue,red"': No such device.
audio/error: Audio device 'dev="Microphone" mics="*"': No such device.
[New Thread 0x7fffd1c5a700 (LWP 31331)]
[New Thread 0x7fffd5c5a700 (LWP 31332)]
opengl/error: Shader dancenote: 0:49(14): warning: `lightDir' used uninitialized

[New Thread 0x7fffd3ab8700 (LWP 31333)]
[New Thread 0x7fffd32b7700 (LWP 31334)]
[New Thread 0x7fffd2ab6700 (LWP 31335)]
[Thread 0x7fffd32b7700 (LWP 31334) exited]
songparser/notice: /usr/share/performous/songs/./songs/restricted/Steven Dunston - Northern Star [DEMO]/Steven Dunston - Northern Star v1.4.txt:
  Not found:      Steven Dunston - Northern Star.MPG
[Thread 0x7fffd2ab6700 (LWP 31335) exited]
[New Thread 0x7fffd1459700 (LWP 31336)]
[New Thread 0x7fffd0c58700 (LWP 31337)]
[New Thread 0x7fffc3fff700 (LWP 31338)]
[New Thread 0x7fffc37fe700 (LWP 31339)]
[New Thread 0x7fffc2ffd700 (LWP 31340)]
[New Thread 0x7fffc27fc700 (LWP 31341)]
[New Thread 0x7fffc1ffb700 (LWP 31342)]
[New Thread 0x7fffc17fa700 (LWP 31343)]
[New Thread 0x7fffc0ff9700 (LWP 31344)]
[New Thread 0x7fffbbfff700 (LWP 31345)]
[New Thread 0x7fffbb7fe700 (LWP 31346)]
[New Thread 0x7fffbaffd700 (LWP 31347)]
[New Thread 0x7fff927ff700 (LWP 31348)]
[New Thread 0x7fffbaffd700 (LWP 31349)]
[Thread 0x7fffbaffd700 (LWP 31347) exited]
[Thread 0x7fff927ff700 (LWP 31348) exited]
[New Thread 0x7fff927ff700 (LWP 31350)]
[New Thread 0x7fffbaffd700 (LWP 31352)]
[Thread 0x7fffbaffd700 (LWP 31349) exited]
[New Thread 0x7fff927ff700 (LWP 31353)]
[Thread 0x7fff927ff700 (LWP 31350) exited]
[New Thread 0x7fff9393f700 (LWP 31354)]
[New Thread 0x7fff9137e700 (LWP 31355)]
[New Thread 0x7fff90b7d700 (LWP 31356)]

Thread 10 "performous" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd3ab8700 (LWP 31333)]
0x00007ffff5c341bc in ?? () from /usr/lib/librsvg-2.so.2
(gdb) backtrace
#0  0x00007ffff5c341bc in  () at /usr/lib/librsvg-2.so.2
#1  0x00007ffff5c31fdd in  () at /usr/lib/librsvg-2.so.2
#2  0x00007ffff5c56242 in  () at /usr/lib/librsvg-2.so.2
#3  0x00007ffff5c37a70 in  () at /usr/lib/librsvg-2.so.2
#4  0x00007ffff5c4244b in  () at /usr/lib/librsvg-2.so.2
#5  0x00007ffff5c42e6b in  () at /usr/lib/librsvg-2.so.2
#6  0x00007ffff5c6b6df in  () at /usr/lib/librsvg-2.so.2
#7  0x00007ffff5c6d9bc in  () at /usr/lib/librsvg-2.so.2
---Type <return> to continue, or q <return> to quit---
#8  0x00007ffff5c3f63e in  () at /usr/lib/librsvg-2.so.2
#9  0x00007ffff5c5563a in  () at /usr/lib/librsvg-2.so.2
#10 0x00007ffff5c3f63e in  () at /usr/lib/librsvg-2.so.2
#11 0x00007ffff5c5563a in  () at /usr/lib/librsvg-2.so.2
#12 0x00007ffff5c71b3f in  () at /usr/lib/librsvg-2.so.2
#13 0x00007ffff5c3f63e in  () at /usr/lib/librsvg-2.so.2
#14 0x00007ffff5c43a9d in rsvg_handle_render_cairo_sub () at /usr/lib/librsvg-2.so.2
#15 0x000000000058a1c4 in loadSVG(Bitmap&, boost::filesystem::path const&) ()
---Type <return> to continue, or q <return> to quit---
#16 0x000000000058917c in SurfaceLoader::Impl::run() ()
#17 0x00007ffff7bc3896 in  () at /usr/lib/libboost_thread.so.1.63.0
#18 0x00007ffff08a0254 in start_thread () at /lib/libpthread.so.0
#19 0x00007ffff05e30ff in clone () at /lib/libc.so.6
(gdb) 
```

Build script:

```
pkgname=performous
pkgver=1.1
pkgrel=1
pkgdesc='Open source game, similar to Singstar, Rockband and Stepmania'
arch=('x86_64')
url="http://performous.org/"
license=('GPL')
depends=('boost-libs' 'glew' 'libxml++' 'portaudio-svn' 'portmidi' 'librsvg' 'ffmpeg' 'opencv' 'sdl2')
makedepends=('cmake' 'pkgconfig' 'help2man' 'boost' 'mesa' 'performous-freesongs')
source=(https://github.com/performous/${pkgname}/archive/${pkgver}.tar.gz)
md5sums=('cf31d0973cd88b3cd626d312d6d3f5b2')

build() {
  cd performous-${pkgver}

  mkdir -p build
  cd build

  cmake -DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr ..

  make
}

package() {
  cd performous-${pkgver}/build

  make DESTDIR="$pkgdir" install
}

```

Steps to reproduce: Start performous, launch default title. (Steven Dunston - Northern Star)

**Comment by ShalokShalom** [comment] 2017-09-18 18:41
OS is KaOS. 

You find the build scripts of the dependencies here: https://github.com/KaOSx

Thanks a lot.

**Comment by Lord-Kamina** [comment] 2017-09-18 19:25
Is this on the stable 1.1?

**Comment by ShalokShalom** [comment] 2017-09-18 20:45
Yes.

**Comment by Baklap4** [comment] 2017-10-03 15:55
@ShalokShalom can you try the current master build?

**Comment by ShalokShalom** [comment] 2017-10-04 20:47
This cause this issue
```

/home/matthias/Projekte/KaOS/makepkg/performous-master/src/performous-master/game/webserver.cc:351:1: Fehler: Redefinition von »WebServer::WebServer(Songs&)«
 WebServer::WebServer(Songs& songs)
 ^~~~~~~~~
In file included from /home/matthias/Projekte/KaOS/makepkg/performous-master/src/performous-master/game/webserver.cc:1:0:
/home/matthias/Projekte/KaOS/makepkg/performous-master/src/performous-master/game/webserver.hh:63:2: Anmerkung: »WebServer::WebServer(Songs&)« previously defined here
  WebServer(Songs&) {}
  ^~~~~~~~~
/home/matthias/Projekte/KaOS/makepkg/performous-master/src/performous-master/game/webserver.cc:353:23: Fehler: Definition des implizit deklarierten »WebServer::~WebServer()«
 WebServer::~WebServer(){}
                       ^
make[2]: *** [game/CMakeFiles/performous.dir/build.make:1575: game/CMakeFiles/performous.dir/webserver.cc.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:159: game/CMakeFiles/performous.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2

```

**Comment by Baklap4** [comment] 2017-10-04 20:51
Possible duplicate of #288 @ShalokShalom can you confirm?

**Comment by Baklap4** [comment] 2018-02-01 16:50
Closing this as duplicate and in favor of #288 
A way to fix this has ben mentioned here: https://github.com/performous/performous/issues/288#issuecomment-341826412

**Closed by Baklap4** 2018-02-01 16:50 UTC
