### ISSUE TITLE
Crash on duet songs

### ISSUE THREAD

**Issue by BWagener** [performous/performous#812] opened 2022-08-22 13:44 UTC
### Performous & operating system versions

Performous: https://github.com/performous/performous/actions/runs/2863890125
OS: Windows 10 Pro N
- Edition	Windows 10 Pro N
- Version	21H2
- Installed on	‎31/‎12/‎2020
- OS build	19044.1826
- Experience	Windows Feature Experience Pack 120.2212.4180.0

### What is the problem?

The game crashes whenever a song is started in duet mode. The songs I've tested with are in UltraStar format.

### Steps to reproduce

1. Start game
2. Enter song selection
3. Hit enter on "Duet mode" or a duet part on a duet song
![image](https://user-images.githubusercontent.com/19321042/185935500-0e0e70fb-a106-49e4-a36a-7bda271e0cdb.png)
4. Game crashes

### Log(s) & preferences file(s)

[config.xml](https://github.com/performous/performous/files/9394784/config.txt)
[database.xml](https://github.com/performous/performous/files/9394785/database.txt)
[infolog.txt](https://github.com/performous/performous/files/9394787/infolog.txt)
[Cat Stevens - Father and Son.txt](https://github.com/performous/performous/files/9394850/Cat.Stevens.-.Father.and.Son.txt)
[Cat Stevens - Father and Son [MULTI].txt](https://github.com/performous/performous/files/9394851/Cat.Stevens.-.Father.and.Son.MULTI.txt)

**Comment by ooshlablu** [comment] 2022-08-22 14:00
I have also noticed this on current master using songs in CloneHero format. This was working fine until a few months ago.

**Comment by BWagener** [comment] 2022-08-22 14:02
> I have also noticed this on current master using songs in CloneHero format. This was working fine until a few months ago.

Thanks! I've tested the 1.2 release and it works on that. I'll try to test some builds in between that and current master to narrow things down.

**Comment by BWagener** [comment] 2022-08-22 15:03
I tested the most recent builds and the last working build in regards to working duet mode is the one for this commit

https://github.com/performous/performous/commit/843511829d5e237534769426a6ca49250a7b34bf
while all builds since, starting with
https://github.com/performous/performous/commit/1512c3c97fe9bf44377573ac58ee45d6c6206440
have this bug.

**Comment by Lord-Kamina** [comment] 2022-08-22 15:14
It's very unlikely that commit is the cause, but most likely something else in the floats PR was. We need a better log and ideally a stack trace.

**Comment by Lord-Kamina** [comment] 2022-08-22 15:18
Could you try older artifacts from the floats branch (look in https://github.com/performous/performous/actions?page=12 and further back) and maybe we can more precisely determine what commit broke it.

**Comment by BWagener** [comment] 2022-08-22 16:02
I agree it's most likely not the commit that the build is from. But I can't seem to find builds for commits between https://github.com/performous/performous/commit/843511829d5e237534769426a6ca49250a7b34bf and https://github.com/performous/performous/commit/1512c3c97fe9bf44377573ac58ee45d6c6206440.

**Comment by Lord-Kamina** [comment] 2022-08-22 16:08
> I agree it's most likely not the commit that the build is from. But I can't seem to find builds for commits between [8435118](https://github.com/performous/performous/commit/843511829d5e237534769426a6ca49250a7b34bf) and [1512c3c](https://github.com/performous/performous/commit/1512c3c97fe9bf44377573ac58ee45d6c6206440).

It's because that PR was force-pushed and rebased a zillion times. So, all builds on the actions tagged fix/floats should be from somewhere between those two.

**Comment by Lord-Kamina** [comment] 2022-08-22 16:33
I just repro'ed the issue. There's a PR for it already but it's not merged (#806)

**Comment by BWagener** [comment] 2022-08-22 20:36
> It's because that PR was force-pushed and rebased a zillion times. So, all builds on the actions tagged fix/floats should be from somewhere between those two.

Ah thanks for explaining. I didn't consider that.

Thanks for finding the underlying problem so quickly! I'm eager to try out the fix but I won't be able to do so until tomorrow.

**Comment by Baklap4** [comment] 2022-09-01 18:04
Just to clarify -> We're doing a division by 0 as `m_step` isn't correctly set as @Lord-Kamina pointed out. This will be fixed in #806

**Closed** 2022-09-06 17:46 UTC
Labels: Bug, Fix Committed
