### ISSUE TITLE
Crash related to covers.

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#298] opened 2017-11-12 16:19 UTC
I was playing for a pretty long while last night and I noticed several crashes... one of them appears to be related to drawing of song covers, although I'm not exactly sure what the issue is.

Here are two separate dumps, they might be related or might be different issues.

[performous_2017-11-12-022153_Anasas copy.log](https://github.com/performous/performous/files/1464861/performous_2017-11-12-022153_Anasas.copy.log)
[performous_2017-11-12-023414_Anasas copy.log](https://github.com/performous/performous/files/1464862/performous_2017-11-12-023414_Anasas.copy.log)

They happened in between songs while playing with a playlist with webserver and autoplay.

**Comment by Baklap4** [comment] 2018-09-17 22:16
Can we recause this in current master? (since it's pretty old already :x)

**Comment by Lord-Kamina** [comment] 2018-09-18 19:16
I haven't seen it again but honestly I don't even know what was the cause initially so...

**Comment by Baklap4** [comment] 2018-09-19 06:36
Then i'll be closing this. If we bump on this again we should recreate/open and write some steps down to reproduce.

**Closed** 2018-09-19 06:36 UTC
Labels: Can't Reproduce
